server:
  port: 8080

core:
  cpu: ENC(hsPPbVVpZ0rZQX6d5oHRNiypCB4n/uHr)

spring:
  rabbitmq:
    host: ENC(h01rbU6zikkzQkVqnqTt7dkwYgzZMjtW)
    username: Forest10
    password: ENC(fofTvXozXUgyTq+WdQ8GFI5Z4Z7ERaciT0iH97INXAI=)
    template:
      retry:
        enabled: true
        initial-interval: 2s
    virtual-host: haha

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD:}
###  --jasypt.encryptor.password=XXXX