server:
  port: 9011

core:
  cpu: Xeno
spring:
  mvc:
    static-path-pattern: /**
  profiles:
    active: @profiles.active@

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD:}
###  --jasypt.encryptor.password=XXXX


