server:
  port: 8080
spring:
  mail:
    protocol: smtp
    host: smtp.qq.com #邮箱服务器地址
    username: 1393679194@qq.com #用户名
    password: ENC(C5WXELlywY9+dzdZy4XOfBqESlxrkEEk0HfHyspHsFk=)
    default-encoding: UTF-8
    fromMail:
      addr: 1393679194@qq.com #以谁来发送邮件
    port: 465
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          starttls:
            enable: true
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD:}




